using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InsertDataToDatabase
{
    public class PlacesData
    {
        public static string[] Places { get; set; } =
        {

"5 Arkansas Trail"
, "3519 Glendale Circle"
, "225 Glacier Hill Court"
, "0 Reinke Alley" 
, "8661 Hanson Terrace       "
, "6261 Meadow Valley Plaza  "
, "84360 Sugar Pass          "
, "85 Florence Center        "
, "481 Corry Junction        "
, "54 Florence Point         "
, "98 Haas Park              "
, "05642 Daystar Parkway     "
, "6 Orin Pass               "
, "29 Express Place          "
, "23 Arapahoe Parkway       "
, "5 Knutson Hill            "
, "99813 Columbus Alley      "
, "70848 Granby Avenue       "
, "015 Briar Crest Court     "
, "15 Havey Avenue           "
, "87 Hagan Street           "
, "19155 Truax Hill          "
, "84 Mendota Court          "
, "1303 Glendale Place       "
, "8688 4th Way              "
, "9857 Anniversary Road     "
, "08578 Roth Hill           "
, "1078 Porter Junction      "
, "2220 Clemons Terrace      "
, "35 Homewood Crossing      "
, "7 Havey Center            "
, "37 Lindbergh Place        "
, "73 Ramsey Junction        "
, "9 Delaware Crossing       "
, "598 Cody Street           "
, "97958 Annamark Terrace    "
, "2345 Toban Road           "
, "223 Forest Run Court      "
, "5 Dorton Trail            "
, "9086 Bultman Hill         "
, "6 Laurel Street           "
, "5 Butternut Trail         "
, "91928 Pine View Plaza     "
, "150 Arrowood Center       "
, "4 Gateway Pass            "
, "72642 Knutson Place       "
, "36015 Elgar Hill          "
, "2237 Shasta Point         "
, "42 Loftsgordon Hill       "
, "2 Arkansas Point          "
, "51 Shasta Avenue          "
, "7 Del Mar Lane            "
, "1 School Lane             "
, "3584 Dottie Avenue        "
, "295 Ridgeway Court        "
, "4266 Corry Parkway        "
, "78244 Badeau Circle       "
, "0447 Bashford Road        "
, "1 Alpine Avenue           "
, "72175 Sunnyside Circle    "
, "62 Duke Point             "
, "0016 Del Mar Road         "
, "24657 Pawling Junction    "
, "0 Oak Valley Crossing     "
, "312 Clarendon Avenue      "
, "52 Barnett Terrace        "
, "118 Loeprich Park         "
, "71 Bartelt Lane           "
, "8581 Coolidge Place       "
, "24472 Waxwing Hill        "
, "06 Shelley Way            "
, "9510 Harbort Road         "
, "90451 Forster Avenue      "
, "4149 Bashford Crossing    "
, "86469 Eastwood Street     "
, "72 Meadow Vale Plaza      "
, "72 Mesta Crossing         "
, "0 Jenifer Place           "
, "3 4th Alley               "
, "2151 Ruskin Way           "
, "50812 Sauthoff Trail      "
, "649 Sutteridge Place      "
, "51068 Havey Parkway       "
, "68 Pierstorff Park        "
, "1 Corry Way               "
, "638 Lakeland Park         "
, "232 Waubesa Junction      "
, "2 1st Lane                "
, "8890 2nd Place            "
, "2 Melody Trail            "
, "351 Carberry Way          "
, "45580 5th Road            "
, "000 Toban Parkway         "
, "65 2nd Place              "
, "32 Hagan Street           "
, "3494 Bellgrove Plaza      "
, "6 1st Center              "
, "541 Sheridan Hill         "
, "9 Ohio Drive              "
, "270 Atwood Alley          "
, "365 Red Cloud Place       "
, "59 Elka Hill              "
, "1503 Westridge Junction   "
, "1152 Springs Lane         "
, "86159 Arrowood Road       "
, "67346 Carpenter Avenue    "
, "4665 Mcguire Lane         "
, "3404 Larry Way            "
, "69 Mallory Plaza          "
, "92 Ilene Hill             "
, "6 Butternut Court         "
, "210 Nova Crossing         "
, "7 Londonderry Plaza       "
, "7 Browning Parkway        "
, "666 Northport Crossing    "
, "319 Golf Place            "
, "13 8th Parkway            "
, "5963 Gale Plaza           "
, "49609 Sloan Street        "
, "890 Washington Park       "
, "3 Mandrake Point          "
, "21691 Blaine Point        "
, "23 Comanche Hill          "
, "85692 Hovde Trail         "
, "79713 Union Terrace       "
, "272 Morning Drive         "
, "03 Bunker Hill Street     "
, "710 Muir Drive            "
, "01288 Del Mar Road        "
, "04 Wayridge Place         "
, "4827 Goodland Street      "
, "10445 Saint Paul Parkway  "
, "46830 Artisan Street      "
, "098 Prentice Parkway      "
, "697 Cascade Pass          "
, "5 Elka Court              "
, "29785 Miller Park         "
, "73 Karstens Junction      "
, "86030 Graceland Center    "
, "20 Rieder Parkway         "
, "7 Bunting Point           "
, "30507 Nancy Point         "
, "475 Browning Avenue       "
, "5 Morning Junction        "
, "54 Ludington Parkway      "
, "7299 Mariners Cove Way    "
, "598 Old Gate Center       "
, "805 Coleman Alley         "
, "63 Stone Corner Park      "
, "53892 Westend Drive       "
, "5 Mesta Point             "
, "853 Kings Court           "
, "0 Kings Pass              "
, "174 Gateway Center        "
, "3 Autumn Leaf Place       "
, "175 Talmadge Way          "
, "452 Tennyson Junction     "
, "968 East Place            "
, "063 Fordem Plaza          "
, "0 Bowman Junction         "
, "768 Beilfuss Crossing     "
, "26 Center Way             "
, "92078 Sauthoff Place      "
, "792 Browning Alley        "
, "177 Paget Road            "
, "3551 Memorial Plaza       "
, "0 Gerald Center           "
, "01 Emmet Place            "
, "20 Rusk Alley             "
, "43 Wayridge Crossing      "
, "215 Cascade Center        "
, "82733 Meadow Vale Terrace "
, "6792 Springview Lane      "
, "3 Eastwood Point          "
, "9 Acker Terrace           "
, "635 Corscot Road          "
, "78445 Stone Corner Alley  "
, "7 Hagan Place             "
, "8 Dottie Alley            "
, "66 Anderson Junction      "
, "110 Carberry Court        "
, "19260 La Follette Crossing"
, "204 Jay Pass              "
, "1199 Pepper Wood Pass     "
, "28032 Mallard Pass        "
, "24 Golden Leaf Lane       "
, "109 Golden Leaf Trail     "
, "99 East Pass              "
, "7099 Erie Pass            "
, "3 Grim Drive              "
, "48 Anhalt Lane            "
, "77329 Maywood Road        "
, "6 Lawn Plaza              "
, "97374 North Way           "
, "884 Arkansas Trail        "
, "4 Thackeray Park          "
, "9 Merrick Way             "
, "51 Esker Alley            "
, "903 Oxford Point          "
, "6985 Dahle Park           "
, "0 Columbus Drive          "
, "36542 Hermina Trail       "
, "233 Elgar Pass            "
, "17929 Scofield Parkway    "
, "109 Maple Wood Point      "
, "19 Meadow Ridge Junction  "
, "95731 Luster Point        "
, "0298 Russell Drive        "
, "02 4th Street             "
, "84617 Jay Center          "
, "24892 Johnson Circle      "
, "6487 Elka Plaza           "
, "108 Comanche Street       "
, "148 Burrows Street        "
, "19 Artisan Pass           "
, "320 Longview Park         "
, "463 Oneill Road           "
, "5554 Dunning Court        "
, "6191 Springs Center       "
, "68 Talisman Crossing      "
, "828 Hanson Terrace        "
, "2 Oriole Road             "
, "8 Sunnyside Crossing      "
, "6 Brentwood Road          "
, "81 Steensland Lane        "
, "15 Arizona Hill           "
, "2733 Upham Court          "
, "691 Porter Avenue         "
, "4 Schlimgen Terrace       "
, "7023 8th Parkway          "
, "857 Merry Lane            "
, "1259 Hazelcrest Trail     "
, "142 Duke Terrace          "
, "296 Hagan Street          "
, "79973 Declaration Alley   "
, "1 Saint Paul Center       "
, "3 Homewood Pass           "
, "7 Lake View Trail         "
, "8296 Nelson Street        "
, "3845 Cambridge Court      "
, "62933 Utah Drive          "
, "9 Ronald Regan Point      "
, "34 Granby Plaza           "
, "1052 Brentwood Terrace    "
, "1913 Graedel Lane         "
, "0 Stang Park              "
, "73 Sycamore Plaza         "
, "0654 Rigney Parkway       "
, "72090 Melvin Place        "
, "3 Blue Bill Park Lane     "
, "6 Elmside Alley           "
, "83 Dakota Way             "
, "59586 Carey Center        "
, "89726 Schurz Point        "
, "25322 Little Fleur Terrace"
, "0 Swallow Court           "
, "41 Barnett Drive          "
, "7 Dwight Park             "
, "2 Di Loreto Crossing      "
, "7026 Logan Lane           "
, "805 Leroy Junction        "
, "98 Alpine Junction        "
, "2 Oak Trail               "
, "6028 Rowland Center       "
, "01774 Hansons Alley       "
, "6949 Dottie Drive         "
, "456 Colorado Junction     "
, "52376 Debs Junction       "
, "635 Everett Lane          "
, "49478 Mendota Alley       "
, "48 Mallory Court          "
, "490 Becker Alley          "
, "27 Waxwing Parkway        "
, "0 Algoma Park             "
, "8306 Ramsey Point         "
, "557 Service Avenue        "
, "981 Loeprich Pass         "
, "25 Prentice Center        "
, "3041 Harper Terrace       "
, "5761 Lakewood Gardens Park"
, "21 Lukken Trail           "
, "557 Bowman Lane           "
, "96 Mallory Terrace        "
, "175 Harper Court          "
, "9 Miller Parkway          "
, "1 Ronald Regan Trail      "
, "713 Vernon Point          "
, "531 Loomis Road           "
, "24799 Havey Center        "
, "2088 Pine View Hill       "
, "29 Anthes Park            "
, "487 Mayfield Lane         "
, "98512 Utah Way            "
, "3 Di Loreto Trail         "
, "7 Troy Point              "
, "3160 Killdeer Lane        "
, "644 Mifflin Drive         "
, "71958 Comanche Pass       "
, "9550 Glendale Road        "
, "34484 Johnson Road        "
, "1612 Butterfield Street   "
, "3242 Golf Course Way      "
, "53168 Canary Trail        "
, "71 Texas Way              "
, "6456 Northland Junction   "
, "58669 Morrow Avenue       "
, "9608 Valley Edge Crossing "
, "9173 Anzinger Circle      "
, "3822 Clemons Place        "
, "6 Nancy Junction          "
, "30423 Eastwood Center     "
, "91188 Welch Parkway       "
, "99 Lunder Junction        "
, "8 Porter Junction         "
, "84 Havey Court            "
, "99288 Nobel Parkway       "
, "5 Sullivan Park           "
, "8 Johnson Crossing        "
, "3444 Oak Center           "
, "235 Bartillon Hill        "
, "5291 Hazelcrest Place     "
, "614 Bultman Avenue        "
, "495 Lakewood Pass         "
, "5695 Hoard Avenue         "
, "0846 Warrior Junction     "
, "57982 Schlimgen Street    "
, "49160 Mendota Point       "
, "576 Paget Place           "
, "3 Crownhardt Crossing     "
, "57 Kedzie Park            "
, "04604 Farwell Road        "
, "5083 Springview Drive     "
, "7 Fallview Lane           "
, "49 Haas Circle            "
, "76 Ohio Court             "
, "6685 Kedzie Circle        "
, "49891 Arkansas Plaza      "
, "9963 Mallory Plaza        "
, "438 Schlimgen Street      "
, "8934 Donald Plaza         "
, "2 Mariners Cove Pass      "
, "8 Anderson Plaza          "
, "471 Almo Point            "
, "5 Trailsway Point         "
, "136 Morning Hill          "
, "9 Stuart Avenue           "
, "08 West Trail             "
, "22131 Alpine Pass         "
, "9 Redwing Court           "
, "8 Vernon Avenue           "
, "2 Everett Place           "
, "574 Jana Terrace          "
, "91382 Morning Junction    "
, "3741 Summerview Way       "
, "98 Dexter Parkway         "
, "0665 Cascade Way          "
, "1 Grayhawk Plaza          "
, "516 3rd Terrace           "
, "5168 Monica Terrace       "
, "78 Summer Ridge Drive     "
, "4388 Springs Center       "
, "2 Sherman Pass            "
, "73384 Division Trail      "
, "5897 Bunker Hill Circle   "
, "96898 Hagan Lane          "
, "80178 Elka Trail          "
, "7395 Thompson Alley       "
, "2 Northview Court         "
, "07814 Stone Corner Place  "
, "807 Moland Drive          "
, "90 Dexter Way             "
, "2 Westridge Park          "
, "8612 Amoth Place          "
, "176 Duke Junction         "
, "851 Tony Circle           "
, "7462 Center Alley         "
, "84685 Coolidge Circle     "
, "61 Rockefeller Circle     "
, "1553 Kings Pass           "
, "17671 Loeprich Park       "
, "51 Autumn Leaf Parkway    "
, "919 Dixon Alley           "
, "8 Graedel Drive           "
, "67 Wayridge Court         "
, "7500 Sugar Crossing       "
, "889 Lukken Road           "
, "032 Alpine Circle         "
, "1330 Ludington Lane       "
, "9 Harbort Court           "
, "2150 Ridge Oak Drive      "
, "680 Dayton Place          "
, "734 Morrow Parkway        "
, "062 Hollow Ridge Terrace  "
, "88476 Sutteridge Pass     "
, "6 Debra Crossing          "
, "6 Comanche Place          "
, "1008 Riverside Street     "
, "2 Shelley Park            "
, "4775 Bluejay Place        "
, "6 Summit Crossing         "
, "6 Division Avenue         "
, "44750 Moland Avenue       "
, "9410 Macpherson Terrace   "
, "957 Lien Place            "
, "298 Sutteridge Alley      "
, "5 Vermont Drive           "
, "44 Longview Trail         "
, "4290 Katie Plaza          "
, "05 Granby Way             "
, "93461 Hintze Way          "
, "036 Eliot Road            "
, "55192 Eagle Crest Park    "
, "0 Killdeer Point          "
, "29 Ridgeview Center       "
, "88443 Cody Pass           "
, "851 Crowley Street        "
, "84669 Mendota Court       "
, "33406 Killdeer Court      "
, "3157 Forest Run Crossing  "
, "120 Algoma Drive          "
, "141 Park Meadow Place     "
, "5755 Dexter Center        "
, "39 Little Fleur Court     "
, "750 Loftsgordon Street    "
, "78879 Kinsman Center      "
, "939 Hoffman Park          "
, "333 Novick Road           "
, "2 Gale Center             "
, "4 Dayton Center           "
, "5 Scoville Avenue         "
, "7 Packers Place           "
, "0 Fordem Hill              "
, "12 Declaration Place      "
, "696 Fairview Pass         "
, "25 Schlimgen Crossing     "
, "9 Delaware Crossing       "
, "4946 International Trail  "
, "9 Gina Circle             "
, "6291 Leroy Hill           "
, "9967 Cordelia Drive       "


        };
    }
}
